export const Users = [
  {
    _id: "1",
    username: "@elon",
    name: "John Mason",
    email: "john.mason@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/21.jpg",
    status: "online",
    lastMessage: "Let me know what you think.",
    time: "Just now",
    messages: [
      {
        _id: "1",
        senderId: "John Mason",
        type: "text",
        content: "Hey there! How are you doing today?",
        time: "10:30 AM",
      },
      {
        _id: "2",
        senderId: "You",
        type: "text",
        content: "I'm doing great! Just working on some new projects.",
        time: "10:32 AM",
      },
    ],
  },
  {
    _id: "2",
    username: "@melissa",
    name: "Melissa Jones",
    email: "melissa.jones@example.com",
    profileImg: "https://randomuser.me/api/portraits/women/32.jpg",
    status: "offline",
    lastMessage: "Let's catch up soon!",
    time: "5 min ago",
    messages: [
      {
        _id: "1",
        senderId: "Melissa Jones",
        type: "text",
        content: "Hey! Are we still on for tomorrow?",
        time: "9:00 AM",
      },
      {
        _id: "2",
        senderId: "You",
        type: "text",
        content: "Yes, absolutely. 4 PM works?",
        time: "9:01 AM",
      },
    ],
  },
  {
    _id: "3",
    username: "@sem",
    name: "Semon",
    email: "",
    profileImg: "https://randomuser.me/api/portraits/men/22.jpg",
    status: "unknown",
    lastMessage: "Check the pull request",
    time: "04/06/2025",
    messages: [
      {
        _id: "1",
        senderId: "@sem",
        type: "text",
        content: "Check the pull request",
        time: "10:00 AM",
      },
      {
        _id: "2",
        senderId: "You",
        type: "text",
        content: "Got it. Reviewing now.",
        time: "10:01 AM",
      },
    ],
  },
  {
    _id: "4",
    username: "@alice",
    name: "Alice",
    email: "",
    profileImg: "https://randomuser.me/api/portraits/women/22.jpg",
    status: "unknown",
    lastMessage: "Can we have a call tomorrow?",
    time: "15/06/2025",
    messages: [
      {
        _id: "1",
        senderId: "@alice",
        type: "text",
        content: "Can we have a call tomorrow?",
        time: "11:00 AM",
      },
      {
        _id: "2",
        senderId: "You",
        type: "text",
        content: "Sure, let me know the time.",
        time: "11:05 AM",
      },
    ],
  },
  {
    _id: "5",
    username: "@sophia",
    name: "Sophia",
    email: "",
    profileImg: "https://randomuser.me/api/portraits/women/12.jpg",
    status: "unknown",
    lastMessage: "Here's the updated UI design",
    time: "07/07/2025",
    messages: [
      {
        _id: "1",
        senderId: "@sophia",
        type: "text",
        content: "Here's the updated UI design",
        time: "3:00 PM",
      },
      {
        _id: "2",
        senderId: "You",
        type: "text",
        content: "Looks good! Clean and minimal.",
        time: "3:02 PM",
      },
    ],
  },
];
